# Tratamento

2017 = Coluna vazia 'unnamed: 14'

In [ ]:
%pip install streamlit pandas openpyxl streamlit-option-menu

In [2]:
%pip list

Package                   Version
------------------------- -----------
altair                    5.5.0
asttokens                 3.0.0
attrs                     25.3.0
blinker                   1.9.0
cachetools                5.5.2
certifi                   2025.4.26
cffi                      1.17.1
charset-normalizer        3.4.2
click                     8.2.0
colorama                  0.4.6
comm                      0.2.2
contourpy                 1.3.1
cycler                    0.12.1
debugpy                   1.8.13
decorator                 5.2.1
et_xmlfile                2.0.0
executing                 2.2.0
fonttools                 4.57.0
gitdb                     4.0.12
GitPython                 3.1.44
h11                       0.16.0
idna                      3.10
ipykernel                 6.29.5
ipython                   9.0.2
ipython_pygments_lexers   1.1.1
jedi                      0.19.2
Jinja2                    3.1.6
jsonschema                4.23.0
jsonschema-specifications 2025.4.1
jupyter_client            8.6.3
jupyter_core              5.7.2
kiwisolver                1.4.8
MarkupSafe                3.0.2
matplotlib                3.10.1
matplotlib-inline         0.1.7
narwhals                  1.39.0
nest-asyncio              1.6.0
numpy                     2.2.4
openpyxl                  3.1.5
outcome                   1.3.0.post0
packaging                 24.2
pandas                    2.2.3
parso                     0.8.4
pillow                    11.1.0
pip                       24.3.1
platformdirs              4.3.6
plotly                    6.0.1
prompt_toolkit            3.0.50
protobuf                  6.30.2
psutil                    7.0.0
pure_eval                 0.2.3
pyarrow                   20.0.0
pycparser                 2.22
pydeck                    0.9.1
Pygments                  2.19.1
pyparsing                 3.2.3
PySocks                   1.7.1
python-dateutil           2.9.0.post0
pytz                      2025.2
pywin32                   309
pyzmq                     26.2.1
referencing               0.36.2
requests                  2.32.3
rpds-py                   0.24.0
selenium                  4.31.0
six                       1.17.0
smmap                     5.0.2
sniffio                   1.3.1
sortedcontainers          2.4.0
stack-data                0.6.3
streamlit                 1.45.1
streamlit-option-menu     0.4.0
tenacity                  9.1.2
toml                      0.10.2
tornado                   6.4.2
traitlets                 5.14.3
trio                      0.30.0
trio-websocket            0.12.2
typing_extensions         4.13.2
tzdata                    2025.2
urllib3                   2.4.0
watchdog                  6.0.0
wcwidth                   0.2.13
websocket-client          1.8.0
wsproto                   1.2.0
Note: you may need to restart the kernel to use updated packages.

In [528]:
import pandas as pd

# ALTERAR ANO DE TRATAMENTO, ex: 2013 = 13, 2014 = 14

ano = 18

df = pd.read_csv(f'./DBs/amlurbcoletatiposresiduos20{ano}.csv', encoding='ISO-8859-1', sep=';')
df.to_excel(f'./DBs_tratados/20{ano}_coleta_tipos_residuos.xlsx', index=False)

# transformar em excel
df = pd.read_excel(f'./DBs_tratados/20{ano}_coleta_tipos_residuos.xlsx')

df

,TIPO DE RES√çDUO,jan/18,fev/18,mar/18,abr/18,mai/18,jun/18,jul/18,ago/18,set/18,out/18,nov/18,dez/18,TOTAL 2018
0,ALIM VENCIDOS,0,0,0,0,0,"5,92",0,0,0,0,0,0,"5,92"
1,ANIMAIS,"2,08","1,80","2,35","2,96","6,15","2,38","3,98","1,70","1,89","4,33","6,03","2,44","38,09"
2,DIVERSOS,"18644,22","18396,62","20431,31","21404,26","15655,92","17537,15","17925,85","18715,00","17496,35","18713,37","20262,06","17488,34","222670,45"
3,DOMICILIAR,"364262,97","290663,37","328072,44","300843,73","302710,48","288833,64","294044,59","301608,39","287203,53","327744,54","309063,10","334787,98","3729838,76"
4,ENTULHO APREENDIDO,"23,24","15,02","14,22",0,0,"6,71",0,0,"6,24","2,99","8,52",0,"76,94"
5,ENTULHO MANUAL,"4851,41","4490,55","5098,62","4639,78","10407,79","4601,27","5175,38","5266,36","4388,46","4287,23","3674,33","3588,97","60470,15"
6,ENTULHO MECANIZADO,"41901,74","39529,16","42499,88","41291,14","38304,43","45147,82","41939,42","45051,74","36047,91","37632,21","22428,83","23304,96","455079,24"
7,ESGOTO,"19667,15","18039,83","18787,17","15991,13","16409,68","14546,36","16385,09","18508,85","17831,45","17657,96","18260,20","19807,23","211892,10"
8,FEIRA LIVRE,"6071,84","5577,81","6236,49","5436,69","4666,12","5437,57","5366,90","5680,90","6106,25","6398,65","6225,89","5945,88","69150,99"
9,GG SAUDE,"2722,67","2540,75","2956,08","2869,01","2911,62","2800,52","2805,82","2930,61","2717,92","2928,47","2727,79","2650,39","33561,65"
10,PG SAUDE,"642,52","616,52","730,04","710,65","717,14","725,12","693,63","800,33","697,43","801,58","723,36","711,01","8569,33"
11,PODA,"3122,83","2176,01","2320,57","2212,91","2736,98","3345,13","3087,89","3790,35","2996,64","3598,30","4092,61","4195,10","37675,32"
12,REJEITO,0,0,0,0,0,0,0,0,0,0,0,0,0
13,REJEITO-CMT CMJ,"1235,86","1025,96","1025,12","1069,42","815,55","918,96","926,39","899,52","826,87","1040,02","955,24","1103,64","11842,55"
14,RESIDUOS DE BOCA DE LOBO,"706,86","756,81","743,83","720,08","809,43","471,09","594,27","595,25","577,81","1133,66","883,76","935,94","8928,79"
15,RESIDUOS DE CORREGOS,"9525,26","6315,12","7077,64","6543,24","5709,84","7405,85","6870,84","6246,03","7224,38","9107,37","8739,84","7950,33","88715,74"
16,RESIDUOS DE ECOPONTO,"30341,43","31229,73","35159,40","32840,68","33690,45","30819,49","36618,21","38597,22","35352,46","37427,67","36072,51","35672,88","413822,13"
17,RESIDUOS DE PISCINAO,"13139,55","16060,13","13445,39","14625,67","14060,70","14869,85","13337,09","13647,67","12762,75","13075,80","17827,14","20267,52","177119,26"
18,SELETIVA,"7735,87","6281,70","6891,00","6485,27","4848,67","6183,86","6010,86","6279,49","5844,25","6673,95","6301,43","7370,23","76906,58"
19,VARRICAO,"7058,05","6837,29","7414,03","6562,55","6785,16","6467,50","6417,94","6825,77","6830,25","6737,53","6258,33","7304,16","81498,56"
20,VARRICAO MECANIZADA,"5,28","1,12",0,"7,65","33,71","149,80","104,19","17,61","19,16",0,"3,28","105,79","447,59"
21,TOTAL,"524597,50","486848,89","534651,55","500877,62","497681,95","486910,69","495068,21","511932,41","481426,59","531602,10","501657,64","529217,84","6082472,99"

In [529]:
# converter numPadr√£o BR > numPadr√£o US

# PARA OS ANOS 2013, 2021
    # Converter blocos espec√≠ficos de cada ano

df.info()

colunas_converter = [f'{mes}/{ano}' for mes in ['jan', 'fev', 'mar', 'abr', 'mai', 'jun', 'jul', 'ago', 'set', 'out', 'nov', 'dez']]


for mes_coluna in colunas_converter:
    df = df.fillna(0)
    df[mes_coluna] = df[mes_coluna].astype(str).str.strip().str.replace(',', '.').str.replace('-', '0').astype(float)

df.columns = df.columns.str.strip()
df.rename(columns={"TIPO DE RES√ñDUO": "Tipo_Residuo", 'TIPO DE RES√çDUO': 'Tipo_Residuo', 'TIPO DE RES√Ø¬ø¬ΩDUO': 'Tipo_Residuo', 'Tipo de Res√≠duo - Toneladas': 'Tipo_Residuo', 'Tipo de res√Ø¬ø¬Ωduo - Toneladas': 'Tipo_Residuo', 'Tipo de res√≠duo - Toneladas': 'Tipo_Residuo', 'Tipo de residuo - Toneladas': 'Tipo_Residuo', f"TOTAL 20{ano}": f"total_20{ano}", f'20{ano}': f'total_20{ano}'}, inplace=True)

df.columns = df.columns.str.lower().str.strip()

df['tipo_residuo'] = df['tipo_residuo'].str.replace('TOTAL', 'total geral')
df['tipo_residuo'] = df['tipo_residuo'].str.lower().str.title()

# tratamento de anos espec√≠ficos
if ano == 20 or ano == 21:
    df[f'total_20{ano}'] = df[colunas_converter].sum(axis=1)
else:
    df[f'total_20{ano}'] = df[f'total_20{ano}'].str.strip().str.replace('.', '').str.replace(',', '.').str.replace('-', '0').astype(float)
    df[f'total_20{ano}'] = df[colunas_converter].sum(axis=1)

if ano == 17:
    df = df.drop(columns='unnamed: 14')

display(df)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22 entries, 0 to 21
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   TIPO DE RES√çDUO  22 non-null     object
 1   jan/18           22 non-null     object
 2   fev/18           22 non-null     object
 3   mar/18           22 non-null     object
 4   abr/18           22 non-null     object
 5   mai/18           22 non-null     object
 6   jun/18           22 non-null     object
 7   jul/18           22 non-null     object
 8   ago/18           22 non-null     object
 9   set/18           22 non-null     object
 10  out/18           22 non-null     object
 11  nov/18           22 non-null     object
 12  dez/18           22 non-null     object
 13  TOTAL 2018       22 non-null     object
dtypes: object(14)
memory usage: 2.5+ KB

,tipo_residuo,jan/18,fev/18,mar/18,abr/18,mai/18,jun/18,jul/18,ago/18,set/18,out/18,nov/18,dez/18,total_2018
0,Alim Vencidos,0.00,0.00,0.00,0.00,0.00,5.92,0.00,0.00,0.00,0.00,0.00,0.00,5.92
1,Animais,2.08,1.80,2.35,2.96,6.15,2.38,3.98,1.70,1.89,4.33,6.03,2.44,38.09
2,Diversos,18644.22,18396.62,20431.31,21404.26,15655.92,17537.15,17925.85,18715.00,17496.35,18713.37,20262.06,17488.34,222670.45
3,Domiciliar,364262.97,290663.37,328072.44,300843.73,302710.48,288833.64,294044.59,301608.39,287203.53,327744.54,309063.10,334787.98,3729838.76
4,Entulho Apreendido,23.24,15.02,14.22,0.00,0.00,6.71,0.00,0.00,6.24,2.99,8.52,0.00,76.94
5,Entulho Manual,4851.41,4490.55,5098.62,4639.78,10407.79,4601.27,5175.38,5266.36,4388.46,4287.23,3674.33,3588.97,60470.15
6,Entulho Mecanizado,41901.74,39529.16,42499.88,41291.14,38304.43,45147.82,41939.42,45051.74,36047.91,37632.21,22428.83,23304.96,455079.24
7,Esgoto,19667.15,18039.83,18787.17,15991.13,16409.68,14546.36,16385.09,18508.85,17831.45,17657.96,18260.20,19807.23,211892.10
8,Feira Livre,6071.84,5577.81,6236.49,5436.69,4666.12,5437.57,5366.90,5680.90,6106.25,6398.65,6225.89,5945.88,69150.99
9,Gg Saude,2722.67,2540.75,2956.08,2869.01,2911.62,2800.52,2805.82,2930.61,2717.92,2928.47,2727.79,2650.39,33561.65
10,Pg Saude,642.52,616.52,730.04,710.65,717.14,725.12,693.63,800.33,697.43,801.58,723.36,711.01,8569.33
11,Poda,3122.83,2176.01,2320.57,2212.91,2736.98,3345.13,3087.89,3790.35,2996.64,3598.30,4092.61,4195.10,37675.32
12,Rejeito,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
13,Rejeito-Cmt Cmj,1235.86,1025.96,1025.12,1069.42,815.55,918.96,926.39,899.52,826.87,1040.02,955.24,1103.64,11842.55
14,Residuos De Boca De Lobo,706.86,756.81,743.83,720.08,809.43,471.09,594.27,595.25,577.81,1133.66,883.76,935.94,8928.79
15,Residuos De Corregos,9525.26,6315.12,7077.64,6543.24,5709.84,7405.85,6870.84,6246.03,7224.38,9107.37,8739.84,7950.33,88715.74
16,Residuos De Ecoponto,30341.43,31229.73,35159.40,32840.68,33690.45,30819.49,36618.21,38597.22,35352.46,37427.67,36072.51,35672.88,413822.13
17,Residuos De Piscinao,13139.55,16060.13,13445.39,14625.67,14060.70,14869.85,13337.09,13647.67,12762.75,13075.80,17827.14,20267.52,177119.26
18,Seletiva,7735.87,6281.70,6891.00,6485.27,4848.67,6183.86,6010.86,6279.49,5844.25,6673.95,6301.43,7370.23,76906.58
19,Varricao,7058.05,6837.29,7414.03,6562.55,6785.16,6467.50,6417.94,6825.77,6830.25,6737.53,6258.33,7304.16,81498.56
20,Varricao Mecanizada,5.28,1.12,0.00,7.65,33.71,149.80,104.19,17.61,19.16,0.00,3.28,105.79,447.59
21,Total Geral,524597.50,486848.89,534651.55,500877.62,497681.95,486910.69,495068.21,511932.41,481426.59,531602.10,501657.64,529217.84,6082472.99

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22 entries, 0 to 21
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   tipo_residuo  22 non-null     object
 1   jan/18        22 non-null     float64
 2   fev/18        22 non-null     float64
 3   mar/18        22 non-null     float64
 4   abr/18        22 non-null     float64
 5   mai/18        22 non-null     float64
 6   jun/18        22 non-null     float64
 7   jul/18        22 non-null     float64
 8   ago/18        22 non-null     float64
 9   set/18        22 non-null     float64
 10  out/18        22 non-null     float64
 11  nov/18        22 non-null     float64
 12  dez/18        22 non-null     float64
 13  total_2018    22 non-null     float64
dtypes: float64(13), object(1)
memory usage: 2.5+ KB

In [530]:
df.to_excel(f'./DBs_tratados/20{ano}_coleta_tipos_residuos.xlsx', index=False)
df

,tipo_residuo,jan/18,fev/18,mar/18,abr/18,mai/18,jun/18,jul/18,ago/18,set/18,out/18,nov/18,dez/18,total_2018
0,Alim Vencidos,0.00,0.00,0.00,0.00,0.00,5.92,0.00,0.00,0.00,0.00,0.00,0.00,5.92
1,Animais,2.08,1.80,2.35,2.96,6.15,2.38,3.98,1.70,1.89,4.33,6.03,2.44,38.09
2,Diversos,18644.22,18396.62,20431.31,21404.26,15655.92,17537.15,17925.85,18715.00,17496.35,18713.37,20262.06,17488.34,222670.45
3,Domiciliar,364262.97,290663.37,328072.44,300843.73,302710.48,288833.64,294044.59,301608.39,287203.53,327744.54,309063.10,334787.98,3729838.76
4,Entulho Apreendido,23.24,15.02,14.22,0.00,0.00,6.71,0.00,0.00,6.24,2.99,8.52,0.00,76.94
5,Entulho Manual,4851.41,4490.55,5098.62,4639.78,10407.79,4601.27,5175.38,5266.36,4388.46,4287.23,3674.33,3588.97,60470.15
6,Entulho Mecanizado,41901.74,39529.16,42499.88,41291.14,38304.43,45147.82,41939.42,45051.74,36047.91,37632.21,22428.83,23304.96,455079.24
7,Esgoto,19667.15,18039.83,18787.17,15991.13,16409.68,14546.36,16385.09,18508.85,17831.45,17657.96,18260.20,19807.23,211892.10
8,Feira Livre,6071.84,5577.81,6236.49,5436.69,4666.12,5437.57,5366.90,5680.90,6106.25,6398.65,6225.89,5945.88,69150.99
9,Gg Saude,2722.67,2540.75,2956.08,2869.01,2911.62,2800.52,2805.82,2930.61,2717.92,2928.47,2727.79,2650.39,33561.65
10,Pg Saude,642.52,616.52,730.04,710.65,717.14,725.12,693.63,800.33,697.43,801.58,723.36,711.01,8569.33
11,Poda,3122.83,2176.01,2320.57,2212.91,2736.98,3345.13,3087.89,3790.35,2996.64,3598.30,4092.61,4195.10,37675.32
12,Rejeito,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
13,Rejeito-Cmt Cmj,1235.86,1025.96,1025.12,1069.42,815.55,918.96,926.39,899.52,826.87,1040.02,955.24,1103.64,11842.55
14,Residuos De Boca De Lobo,706.86,756.81,743.83,720.08,809.43,471.09,594.27,595.25,577.81,1133.66,883.76,935.94,8928.79
15,Residuos De Corregos,9525.26,6315.12,7077.64,6543.24,5709.84,7405.85,6870.84,6246.03,7224.38,9107.37,8739.84,7950.33,88715.74
16,Residuos De Ecoponto,30341.43,31229.73,35159.40,32840.68,33690.45,30819.49,36618.21,38597.22,35352.46,37427.67,36072.51,35672.88,413822.13
17,Residuos De Piscinao,13139.55,16060.13,13445.39,14625.67,14060.70,14869.85,13337.09,13647.67,12762.75,13075.80,17827.14,20267.52,177119.26
18,Seletiva,7735.87,6281.70,6891.00,6485.27,4848.67,6183.86,6010.86,6279.49,5844.25,6673.95,6301.43,7370.23,76906.58
19,Varricao,7058.05,6837.29,7414.03,6562.55,6785.16,6467.50,6417.94,6825.77,6830.25,6737.53,6258.33,7304.16,81498.56
20,Varricao Mecanizada,5.28,1.12,0.00,7.65,33.71,149.80,104.19,17.61,19.16,0.00,3.28,105.79,447.59
21,Total Geral,524597.50,486848.89,534651.55,500877.62,497681.95,486910.69,495068.21,511932.41,481426.59,531602.10,501657.64,529217.84,6082472.99