# Tratamento

2017 = Coluna vazia 'unnamed: 14'

In [1]:
# %pip install pandas openpyxl

In [2]:
import pandas as pd

# ALTERAR ANO DE TRATAMENTO, ex: 2013 = 13, 2014 = 14

ano = 21

df = pd.read_csv(f'./DBs/amlurbcoletatiposresiduos20{ano}.csv', encoding='ISO-8859-1', sep=';')
df.to_excel(f'./DBs_tratados/20{ano}_coleta_tipos_residuos.xlsx', index=False)

# transformar em excel
df = pd.read_excel(f'./DBs_tratados/20{ano}_coleta_tipos_residuos.xlsx')

df

                        Tipo de resï¿½duo - Toneladas     jan/21     fev/21
0                                          DOMICILIAR   308.771    278.866
1                                  ENTULHO MECANIZADO     7.807      7.117
2                                RESIDUOS DE ECOPONTO    28.024     27.865
3                                            DIVERSOS    27.866     24.265
4                                              ESGOTO    16.607     16.613
5                                RESIDUOS DE PISCINAO    16.395     18.258
6                                RESIDUOS DE CORREGOS    22.680     20.375
7                                            VARRICAO     5.298      6.944
8                                            SELETIVA     7.651      6.647
9                                         FEIRA LIVRE     6.303      5.874
10                                     ENTULHO MANUAL     1.127      1.122
11                                               PODA     6.102      5.836
12                                           GG SAUDE     3.370      3.334
13                                    REJEITO-CMT CMJ     1.648      1.276
14                           RESIDUOS DE BOCA DE LOBO     1.468      1.794
15                                           PG SAUDE       753        813
16                       REMOCAO RESIDUOS DESCARTADOS       -          -
17                         RESIDUOS PATIO COMPOSTAGEM       -          -
18                                            REJEITO       -          -
19                                 ENTULHO APREENDIDO       -          -
20                                            MADEIRA     5.808      5.582
21                                            ANIMAIS         1          2
22                                VARRICAO MECANIZADA       374        499
23                                      ALIM VENCIDOS       -          -
24                               RESIDUO DE APREENSAO       240        247
25                              RESIDUO DE ACUMULADOR        30         93
26                            RESIDUO DE DESFAZIMENTO        54        253
27  EQUIPE DE EVENTOS ESPECIAIS E OPERACOES DE EME...       -          -
28                         RESIDUO ECOPONTO - ENTULHO     4.074      5.825
29                                  ENTULHO DO PREDIO       -          -
30                                     LIMPEZA URBANA       -          -
31                    RESIDUOS DE ECOPONTO - DIVERSOS       268        304
32                                        Total geral   472.719    439.805

In [3]:
# converter numPadrão BR > numPadrão US

# PARA OS ANOS 2013, 2021
    # Converter blocos específicos de cada ano

df.info()

colunas_converter = [f'{mes}/{ano}' for mes in ['jan', 'fev', 'mar', 'abr', 'mai', 'jun', 'jul', 'ago', 'set', 'out', 'nov', 'dez']]


for mes_coluna in colunas_converter:
    df = df.fillna(0)
    df[mes_coluna] = df[mes_coluna].astype(str).str.strip().str.replace(',', '.').str.replace('-', '0').astype(float)

df.columns = df.columns.str.strip()
df.rename(columns={"TIPO DE RESÖDUO": "Tipo_Residuo", 'TIPO DE RESÍDUO': 'Tipo_Residuo', 'TIPO DE RESï¿½DUO': 'Tipo_Residuo', 'Tipo de Resíduo - Toneladas': 'Tipo_Residuo', 'Tipo de resï¿½duo - Toneladas': 'Tipo_Residuo', 'Tipo de resíduo - Toneladas': 'Tipo_Residuo', 'Tipo de residuo - Toneladas': 'Tipo_Residuo', f"TOTAL 20{ano}": f"total_20{ano}", f'20{ano}': f'total_20{ano}'}, inplace=True)

df.columns = df.columns.str.lower().str.strip()

df['tipo_residuo'] = df['tipo_residuo'].str.replace('TOTAL', 'total geral')
df['tipo_residuo'] = df['tipo_residuo'].str.lower().str.title()

df = df[df['tipo_residuo'] != '(Vazio)']

# tratamento de anos específicos
if ano == 20 or ano == 21:
    df[f'total_20{ano}'] = df[colunas_converter].sum(axis=1)
else:
    df[f'total_20{ano}'] = df[f'total_20{ano}'].str.strip().str.replace('.', '').str.replace(',', '.').str.replace('-', '0').astype(float)
    df[f'total_20{ano}'] = df[colunas_converter].sum(axis=1)

if ano == 17:
    df = df.drop(columns='unnamed: 14')
elif ano == 24:
    df = df.drop(columns='unnamed: 13')

display(df)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33 entries, 0 to 32
Data columns (total 3 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Tipo de resï¿½duo - Toneladas  33 non-null     object
 1   jan/21                         33 non-null     object
 2   fev/21                         33 non-null     object
dtypes: object(3)
memory usage: 924.0+ bytes

,tipo_residuo,jan/21,fev/21,total_2021
0,Domiciliar,308.771,278.866,587.637
1,Entulho Mecanizado,7.807,7.117,14.924
2,Residuos De Ecoponto,28.024,27.865,55.889
3,Diversos,27.866,24.265,52.131
4,Esgoto,16.607,16.613,33.220
5,Residuos De Piscinao,16.395,18.258,34.653
6,Residuos De Corregos,22.680,20.375,43.055
7,Varricao,5.298,6.944,12.242
8,Seletiva,7.651,6.647,14.298
9,Feira Livre,6.303,5.874,12.177
10,Entulho Manual,1.127,1.122,2.249
11,Poda,6.102,5.836,11.938
12,Gg Saude,3.370,3.334,6.704
13,Rejeito-Cmt Cmj,1.648,1.276,2.924
14,Residuos De Boca De Lobo,1.468,1.794,3.262
15,Pg Saude,753.000,813.000,1566.000
16,Remocao Residuos Descartados,0.000,0.000,0.000
17,Residuos Patio Compostagem,0.000,0.000,0.000
18,Rejeito,0.000,0.000,0.000
19,Entulho Apreendido,0.000,0.000,0.000
20,Madeira,5.808,5.582,11.390
21,Animais,1.000,2.000,3.000
22,Varricao Mecanizada,374.000,499.000,873.000
23,Alim Vencidos,0.000,0.000,0.000
24,Residuo De Apreensao,240.000,247.000,487.000
25,Residuo De Acumulador,30.000,93.000,123.000
26,Residuo De Desfazimento,54.000,253.000,307.000
27,Equipe De Eventos Especiais E Operacoes De Eme...,0.000,0.000,0.000
28,Residuo Ecoponto - Entulho,4.074,5.825,9.899
29,Entulho Do Predio,0.000,0.000,0.000
30,Limpeza Urbana,0.000,0.000,0.000
31,Residuos De Ecoponto - Diversos,268.000,304.000,572.000
32,Total Geral,472.719,439.805,912.524

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33 entries, 0 to 32
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   tipo_residuo  33 non-null     object
 1   jan/21        33 non-null     float64
 2   fev/21        33 non-null     float64
 3   total_2021    33 non-null     float64
dtypes: float64(3), object(1)
memory usage: 1.2+ KB

In [4]:
df.to_excel(f'./DBs_tratados/20{ano}_coleta_tipos_residuos.xlsx', index=False)
df

,tipo_residuo,jan/21,fev/21,total_2021
0,Domiciliar,308.771,278.866,587.637
1,Entulho Mecanizado,7.807,7.117,14.924
2,Residuos De Ecoponto,28.024,27.865,55.889
3,Diversos,27.866,24.265,52.131
4,Esgoto,16.607,16.613,33.220
5,Residuos De Piscinao,16.395,18.258,34.653
6,Residuos De Corregos,22.680,20.375,43.055
7,Varricao,5.298,6.944,12.242
8,Seletiva,7.651,6.647,14.298
9,Feira Livre,6.303,5.874,12.177
10,Entulho Manual,1.127,1.122,2.249
11,Poda,6.102,5.836,11.938
12,Gg Saude,3.370,3.334,6.704
13,Rejeito-Cmt Cmj,1.648,1.276,2.924
14,Residuos De Boca De Lobo,1.468,1.794,3.262
15,Pg Saude,753.000,813.000,1566.000
16,Remocao Residuos Descartados,0.000,0.000,0.000
17,Residuos Patio Compostagem,0.000,0.000,0.000
18,Rejeito,0.000,0.000,0.000
19,Entulho Apreendido,0.000,0.000,0.000
20,Madeira,5.808,5.582,11.390
21,Animais,1.000,2.000,3.000
22,Varricao Mecanizada,374.000,499.000,873.000
23,Alim Vencidos,0.000,0.000,0.000
24,Residuo De Apreensao,240.000,247.000,487.000
25,Residuo De Acumulador,30.000,93.000,123.000
26,Residuo De Desfazimento,54.000,253.000,307.000
27,Equipe De Eventos Especiais E Operacoes De Eme...,0.000,0.000,0.000
28,Residuo Ecoponto - Entulho,4.074,5.825,9.899
29,Entulho Do Predio,0.000,0.000,0.000
30,Limpeza Urbana,0.000,0.000,0.000
31,Residuos De Ecoponto - Diversos,268.000,304.000,572.000
32,Total Geral,472.719,439.805,912.524

In [5]:
# converter numPadrão BR > numPadrão US

# PARA OS ANOS 2013, 2021
    # Converter blocos específicos de cada ano

df.info()

colunas_converter = [f'{mes}/{ano}' for mes in ['jan', 'fev', 'mar', 'abr', 'mai', 'jun', 'jul', 'ago', 'set', 'out', 'nov', 'dez']]

df.columns = df.columns.str.strip()

for mes_coluna in colunas_converter:
    df = df.fillna(0)
    df[mes_coluna] = df[mes_coluna].astype(str).str.strip().str.replace(',', '.').str.replace('-', '0').astype(float)

df.rename(columns={"TIPO DE RESÖDUO": "Tipo_Residuo", 'TIPO DE RESÍDUO': 'Tipo_Residuo', 'TIPO DE RESï¿½DUO': 'Tipo_Residuo', 'Tipo de Resíduo - Toneladas': 'Tipo_Residuo', 'Tipo de resï¿½duo - Toneladas': 'Tipo_Residuo', 'Tipo de resíduo - Toneladas': 'Tipo_Residuo', 'Tipo de residuo - Toneladas': 'Tipo_Residuo', f"TOTAL 20{ano}": f"total_20{ano}", f'20{ano}': f'total_20{ano}'}, inplace=True)

df.columns = df.columns.str.lower().str.strip()

df['tipo_residuo'] = df['tipo_residuo'].str.replace('TOTAL', 'total geral')
df['tipo_residuo'] = df['tipo_residuo'].str.lower().str.title()

df = df[df['tipo_residuo'] != '(Vazio)']

# tratamento de anos específicos
if ano == 20 or ano == 21:
    df[f'total_20{ano}'] = df[colunas_converter].sum(axis=1)
else:
    df[f'total_20{ano}'] = df[f'total_20{ano}'].str.strip().str.replace('.', '').str.replace(',', '.').str.replace('-', '0').astype(float)
    df[f'total_20{ano}'] = df[colunas_converter].sum(axis=1)

if ano == 17:
    df = df.drop(columns='unnamed: 14')
elif ano == 24:
    df = df.drop(columns='unnamed: 13')

display(df)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33 entries, 0 to 32
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   tipo_residuo  33 non-null     object
 1   jan/21        33 non-null     float64
 2   fev/21        33 non-null     float64
 3   total_2021    33 non-null     float64
dtypes: float64(3), object(1)
memory usage: 1.2+ KB

KeyError: 'mar/21'